export const LANDING = '/'
export const RECIPES = '/recipes'
export const ADD_RECIPE = '/recipes/add'
export const SINGLE_RECIPE = '/recipes/:id'
export const SEARCH = '/search'
export const SIGNUP = '/signup'
export const LOGIN = '/login'
export const PASSWORD_FORGET = '/passwordforget'
